print("########################################")
print("#                                      #")
print("#           ___  ___  ___              #")
print("#          |__ \\|__ \\|__ \\             #")
print("#             ) |  ) |  ) |            #")
print("#            / /  / /  / /             #")
print("#           / /_ / /_ / /_             #")
print("#          |____|____|____|            #")
print("#                                      #")
print("#       Willkommen beim Taxirechner    #")
print("#                                      #")
print("########################################")
print("")
km = input("Wie viele Kilometer möchtest du fahren? ")
result = 5.7 + float(km) * 2.5
print("")
print(f"Die Taxifahrt kostet {result}€.")
input("Drücke Enter")